### ISSUE TITLE
Impossible to login with Windows Hello Hardware Authenticator

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#374] opened 2023-01-26 10:33 UTC
### Version(s) affected

4.5.0
4.5.1

### Description

Hi,

Possible same problem of #372

When i try to login with a Windows Hello Hardware Authenticator, i have this error : 

```
{
     "status":"error",
     "errorMessage":"Warning: openssl_verify(): Supplied key param cannot be coerced into a public key"
}
```

My openssl version : 
`OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)`

### How to reproduce

POST OPTION : 
```
{
    "attestation": "direct",
    "authenticatorSelection": {
        "requireResidentKey": true,
        "userVerification": "required"
    }
}
```

RESPONSE OPTION : 
```
{"challenge":"t92hKb5JZ1Rj4v76GASWw4VNm_RNnoGYXz9bl1h3Duw","rpId":"localhost","userVerification":"required","status":"ok","errorMessage":""}
```

POST LOGIN : 
```
{"id":"f3xLMoBLBsFIC85SNSeM1ull_uGszpDYROxM_b800oE","rawId":"f3xLMoBLBsFIC85SNSeM1ull_uGszpDYROxM_b800oE","response":{"authenticatorData":"SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2MFAAAAAQ","clientDataJSON":"eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoidDkyaEtiNUpaMVJqNHY3NkdBU1d3NFZObV9STm5vR1lYejlibDFoM0R1dyIsIm9yaWdpbiI6Imh0dHBzOi8vbG9jYWxob3N0OjgwMDAiLCJjcm9zc09yaWdpbiI6ZmFsc2V9","signature":"PGRj0rCbEunG0Bg_cEhorLP7nOsiTkoTgSFsV_m-yIlp_keZiRF2yRCDKFg81GQz3xVMkoN4ku3NLZAuiuw1M-brudE4xQyprPqXCBGOdcX6R6AoWE9j0M9bWfVIjJ2H0NO-e01lqoy4Otmq7kKgVdpZgMmFg3tYx3Sp9qYtttOHsW8GBgVjAtl3DoHdXFnQFkzpeD9G-NTvqlSaAqCGgeb9JVJhF-E18ZNDOVz_d2v-j-NhBN8pfslnURvI9bPA0CeDZUP7_W4pdQkbA1ltwvLpc91Uxa1TSQ1lJyxo1lq1qdj5FRd-ukYu5cXutJuUbFAwpP34DMFBtVz3KJB9Uw","userHandle":"dGJveWVyQGVjb3dhbi5mcg"},"type":"public-key","clientExtensionResults":{}}
```

RESPONSE LOGIN : 
```
{
     "status":"error",
     "errorMessage":"Warning: openssl_verify(): Supplied key param cannot be coerced into a public key"
}
```

PUBLIC KEY : 
```
pAEDAzkBACBZAQCxYInAO/MBDayy5fsYhAmflU7hw4aLgwl7oDSbPAD79h1mULDm0lo5lxJ4uIW6cQJ0m24j2V1xBqwXxmwaotKv3w7blZ0YeIPdH7Pi/QpbymQloNUAvaFlKQWXJQnbLpV++d2l7Sh7ZoKwhd0SYdI7STh1rhsZY0IE1Ya7MJX1R/763evMsGL2Q62dKuVN8SmfECta6HJJDAkN5AuEEp2a6BQtC6BV9OekhIrbdareGQ5/PtfIuYCAshGETivCyIO0LRxhEDuv2KKndVzyHbEBXnLT7WDj643koVXjMPGoHL3xXjeHmxknpQFwkffq3rKx0Pm7H3ZKuk95rNxJMKoTIUMBAAE=
```

**Comment by Spomky** [comment] 2023-01-27 14:25
🤔That is strange. I remember have such issue in the past, but this should be fixed now.
I am wondering if the absence of the GMP extension can cause this.
I will investigate more.

**Comment by lukewarlow** [comment] 2023-01-31 12:01
I'd just like to add that I've also come across this issue. Exact same error message, and specifically only with Windows Hello. Android and macOS platform authenticators work fine along with YubiKeys.

Output from `php -i | grep OpenSSL` if that helps.

openssl

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.1s  1 Nov 2022
OpenSSL Header Version => OpenSSL 1.1.1s  1 Nov 2022
Openssl default config => C:\Program Files\Common Files\SSL/openssl.cnf

Directive => Local Value => Master Value
openssl.cafile => no value => no value
openssl.capath => no value => no value

**Comment by Spomky** [comment] 2023-01-31 17:24
Hi @tydoo,

Could you please share the public key credential source?
I cannot reproduce the error without the public key associated to the ID `JMCARryti6KT_TmZh8SpeAVuz_z01tViA70TAaHTNc0`.

Many thanks.
Regards.

**Comment by tydoo** [comment] 2023-01-31 17:53
I have try with the id `RG09nM_K_G-IVFzAwn0vObHLptHfmm-KE5xj-RMk6Z8`.

Public key : 

```
pAEDAzkBACBZAQDP+dW+puca4MZcJAzaV9WFqE6FF91KiNiUP0CGl0VNzNxn8IinqzEicPTPHcG+MCE+pw7QzyHdKtoqB15FD5iPEwXp5to2S4p31YT5VCglYiZf7IEuvb+go7rzN3zEpTnTVwpuLHHZsTaeWoGOa8xKlR27VCpyhdLQ9p6wnRZeuMrVUwXWylYNvB/oiIYjkksRVT3PBh6QOxlkfdEK14aiWe423p64V5DxZn0nAc0fgv7VxzmDZV3DJJr3I79goQ3zhfGty7ujQ9raLi7YxyemKikv9vhhsx9qiu8gCx/9U3da7IuLhBlfMUiNrgIyJv8Lk/nbzlePLy4FuCWHY7kjIUMBAAE=
```

**Comment by Spomky** [comment] 2023-01-31 18:15
Thanks,

I have an `Invalid signature exception`. THis makes sense as the key you provided does not correspond to the options/response provided few days ago.
But the key is still valid and correctly converted.

In the abstract class `Cose\Algorithm\Signature\RSA\RSA`, could you please dump the key (PEM format) used to verify the signature at line 36 (just before the `openss_verify` call)?
The result with the previous public key is as follows:

```
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAz/nVvqbnGuDGXCQM2lfVhahOhRfdSojYlD9AhpdFTczcZ/CIp6sx
InD0zx3BvjAhPqcO0M8h3SraKgdeRQ+YjxMF6ebaNkuKd9WE+VQoJWImX+yBLr2/
oKO68zd8xKU501cKbixx2bE2nlqBjmvMSpUdu1QqcoXS0PaesJ0WXrjK1VMF1spW
Dbwf6IiGI5JLEVU9zwYekDsZZH3RCteGolnuNt6euFeQ8WZ9JwHNH4L+1cc5g2Vd
wySa9yO/YKEN84Xxrcu7o0Pa2i4u2McnpiopL/b4YbMfaorvIAsf/VN3WuyLi4QZ
XzFIja4CMib/C5P5285Xjy8uBbglh2O5IwIDAQAB
-----END RSA PUBLIC KEY-----
```

ASN1 structure:
```
SEQUENCE (2 elem)
  INTEGER (2048 bit) 262545273287294685341406007318437641989513372451060770260515679691064…
  INTEGER 65537
```

**Comment by Spomky** [comment] 2023-01-31 18:17
Can you also dump the Key object?
Should be something like that:

```
Cose\Key\RsaKey {#169
  -data: array:4 [
    1 => "3"
    3 => "-257"
    -1 => b"""
      ¤¨ı¥ªþ\x1AÓã\$\f┌Wıà¿Nà\x17¦JêÏö?@åùEM╠▄g­êº½1"p¶¤\x1D┴¥0!>º\x0Eð¤!¦*┌*\x07^E\x0FÿÅ\x13\x05Úµ┌6Kèwıä¨T(%b&_ýü.¢┐áú║¾7|─Ñ9ËW\n
      n,q┘▒6×ZüÄk╠Jò\x1D╗T*ràÊð÷×░Ø\x16^©╩ıS\x05Í╩V\r╝\x1FÞêå#ÆK\x11U=¤\x06\x1EÉ;\x19d}Ð\n
      ÎåóY¯6Ì×©WÉ±f}'\x01═\x1Fé■ıÃ9âe]├$Ü¸#┐`í\r¾à±¡╦╗úC┌┌..ÏÃ'ª*)/÷°a│\x1Fjè´ \v\x1F²SwZýïïä\x19_1Hì«\x022& \vô¨█╬WÅ/.\x05©%çc╣#
      """
    -2 => "\x01\x00\x01"
  ]
}
```

**Comment by tydoo** [comment] 2023-01-31 18:38
Sorry.

No because i have send the public key of id `RG09nM_K_G-IVFzAwn0vObHLptHfmm-KE5xj-RMk6Z8` after change pc.

I have updated all informations on my first message.

**Comment by Spomky** [comment] 2023-01-31 19:12
Thnaks. But honestly I don't get it...

The assertion is correctly validated on my side.

```php
<?php

declare(strict_types=1);

namespace Webauthn\Tests\Functional;

use ParagonIE\ConstantTime\Base64UrlSafe;
use Symfony\Component\Uid\Uuid;
use Webauthn\AuthenticatorAssertionResponse;
use Webauthn\PublicKeyCredentialRequestOptions;
use Webauthn\Tests\MemoryPublicKeyCredentialSourceRepository;

/**
 * @internal
 */
final class AssertionTest extends AbstractTestCase
{
    /**
     * @test
     */
    public function anAssertionCanBeVerified2(): void
    {
        $publicKeyCredentialRequestOptions = PublicKeyCredentialRequestOptions::createFromString('{"challenge":"t92hKb5JZ1Rj4v76GASWw4VNm_RNnoGYXz9bl1h3Duw","rpId":"localhost","userVerification":"required","status":"ok","errorMessage":""}');
        $publicKeyCredential = $this->getPublicKeyCredentialLoader()
            ->load('{"id":"f3xLMoBLBsFIC85SNSeM1ull_uGszpDYROxM_b800oE","rawId":"f3xLMoBLBsFIC85SNSeM1ull_uGszpDYROxM_b800oE","response":{"authenticatorData":"SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2MFAAAAAQ","clientDataJSON":"eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoidDkyaEtiNUpaMVJqNHY3NkdBU1d3NFZObV9STm5vR1lYejlibDFoM0R1dyIsIm9yaWdpbiI6Imh0dHBzOi8vbG9jYWxob3N0OjgwMDAiLCJjcm9zc09yaWdpbiI6ZmFsc2V9","signature":"PGRj0rCbEunG0Bg_cEhorLP7nOsiTkoTgSFsV_m-yIlp_keZiRF2yRCDKFg81GQz3xVMkoN4ku3NLZAuiuw1M-brudE4xQyprPqXCBGOdcX6R6AoWE9j0M9bWfVIjJ2H0NO-e01lqoy4Otmq7kKgVdpZgMmFg3tYx3Sp9qYtttOHsW8GBgVjAtl3DoHdXFnQFkzpeD9G-NTvqlSaAqCGgeb9JVJhF-E18ZNDOVz_d2v-j-NhBN8pfslnURvI9bPA0CeDZUP7_W4pdQkbA1ltwvLpc91Uxa1TSQ1lJyxo1lq1qdj5FRd-ukYu5cXutJuUbFAwpP34DMFBtVz3KJB9Uw","userHandle":"dGJveWVyQGVjb3dhbi5mcg"},"type":"public-key","clientExtensionResults":{}}');
        static::assertInstanceOf(AuthenticatorAssertionResponse::class, $publicKeyCredential->getResponse());
        $publicKeyCredentialSource = $this->createPublicKeyCredentialSource(
            Base64UrlSafe::decodeNoPadding(
                'f3xLMoBLBsFIC85SNSeM1ull_uGszpDYROxM_b800oE'
            ),
            'tboyer@ecowan.fr',
            0,
            Uuid::fromString('00000000-0000-0000-0000-000000000000'),
            base64_decode(
                'pAEDAzkBACBZAQCxYInAO/MBDayy5fsYhAmflU7hw4aLgwl7oDSbPAD79h1mULDm0lo5lxJ4uIW6cQJ0m24j2V1xBqwXxmwaotKv3w7blZ0YeIPdH7Pi/QpbymQloNUAvaFlKQWXJQnbLpV++d2l7Sh7ZoKwhd0SYdI7STh1rhsZY0IE1Ya7MJX1R/763evMsGL2Q62dKuVN8SmfECta6HJJDAkN5AuEEp2a6BQtC6BV9OekhIrbdareGQ5/PtfIuYCAshGETivCyIO0LRxhEDuv2KKndVzyHbEBXnLT7WDj643koVXjMPGoHL3xXjeHmxknpQFwkffq3rKx0Pm7H3ZKuk95rNxJMKoTIUMBAAE=',
                true
            )
        );
        $credentialRepository = new MemoryPublicKeyCredentialSourceRepository();
        $credentialRepository->saveCredentialSource($publicKeyCredentialSource);
        $this->getAuthenticatorAssertionResponseValidator($credentialRepository)
            ->check(
                $publicKeyCredential->getRawId(),
                $publicKeyCredential->getResponse(),
                $publicKeyCredentialRequestOptions,
                'localhost',
                'tboyer@ecowan.fr'
            );
        static::assertSame(1, $publicKeyCredentialSource->getCounter());
    }
}
```

I am pretty sure there is something wrong with the RSA algorithm, but I cannot figure out what.
It is important to me to know what is sent to the `openssl_verify` function.
Can you dump the input data I mentioned above and share the values? (make sure you have `symfony/var-dumper` installed as dev dependency)

```
    public function verify(string $data, Key $key, string $signature): bool
    {
        $key = $this->handleKey($key);
        dump($key, $key->toPublic()->asPem()); // This line is important

        return openssl_verify($data, $signature, $key->toPublic()->asPem(), $this->getHashAlgorithm()) === 1;
    }
```

EDIT: By the way, I tested with GMP, BCMath or without those 2 extensions and the result is the same: the tests pass

**Comment by tydoo** [comment] 2023-02-01 10:07
**Dumped Contents**

In [RSA.php](vscode://file/C:\Users\thomas\OneDrive\Documents\Developpement web\Sites web\lebackoffice\vendor\web-auth\cose-lib\src\Algorithm\Signature\RSA\RSA.php:33) line 33:
```
[Cose\Key\RsaKey](vscode://file/C:\Users\thomas\OneDrive\Documents\Developpement web\Sites web\lebackoffice\vendor\web-auth\cose-lib\src\Key\RsaKey.php:17) {#2556 ▼
  -data: array:4 [▼
    1 => "3"
    3 => "-257"
    -1 => b"▒`ë└;¾\x01\r¼▓Õ¹\x18ä\tƒòNß├åïâ\t{á4ø<\x00¹÷\x1DfP░µÊZ9ù\x12x©à║q\x02tøn#┘]q\x06¼\x17ãl\x1AóÊ»▀\x0E█òØ\x18xâ¦\x1F│Ô²\n[╩d%áı\x00¢íe)\x05ù%\t█.ò~¨¦ÑÝ({fé░à¦\x12a ▶"
    -2 => "\x01\x00\x01"
  ]
}
```

In [RSA.php](vscode://file/C:\Users\thomas\OneDrive\Documents\Developpement web\Sites web\lebackoffice\vendor\web-auth\cose-lib\src\Algorithm\Signature\RSA\RSA.php:33) line 33:
```
"""
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAsWCJwDvzAQ2ssuX7GIQJn5VO4cOGi4MJe6A0mzwA+/YdZlCw5tJa
OZcSeLiFunECdJtuI9ldcQasF8ZsGqLSr98O25WdGHiD3R+z4v0KW8pkJaDVAL2h
ZSkFlyUJ2y6Vfvndpe0oe2aCsIXdEmHSO0k4da4bGWNCBNWGuzCV9Uf++t3rzLBi
9kOtnSrlTfEpnxArWuhySQwJDeQLhBKdmugULQugVfTnpISK23Wq3hkOfz7XyLmA
gLIRhE4rwsiDtC0cYRA7r9iip3Vc8h2xAV5y0+1g4+uN5KFV4zDxqBy98V43h5sZ
J6UBcJH36t6ysdD5ux92SrpPeazcSTCqEwIDAQAB
-----END RSA PUBLIC KEY-----
"""
```

**Comment by hdimitrov1** [comment] 2023-02-01 13:39
@tydoo  and anyone looking at this issue.

At the time of this comment you can pin the version of `web-auth/cose-lib` to 4.0.12 and that will make this package work

To do this, add this to composer.json
```
"web-auth/cose-lib": "4.0.12",
```

**Comment by Spomky** [comment] 2023-02-01 13:50
Hi @hdimitrov1,

Many thanks for this advice and feedback.
I focused on the RSA algorithm and OpenSSL, but I think you are right and this may be caused by a mix of the 2.
Whilst the PEM key shared here seem to be valid, some older versions of OpenSSL only accept public keys with a specific format.
`web-auth/cose-lib` v4.1 changed one (unmaintained) dependency, but it seems the PEM encoding of the RSA public keys is causing these difficulties. I will change that ASAP.
In the meantime, if 4.0 works fine, please use it.

**Comment by Spomky** [comment] 2023-02-01 20:34
Hi,

I have just release web-auth/cose-liv 4.1.1
This should fix this issue and #372.
Can you confirm it is the case or if the issue is still there?

ping @hdimitrov1 , @lukewarlow , @tydoo , @Nevercold

**Comment by tydoo** [comment] 2023-02-01 21:26
@Spomky Yes, after update its works ;)

**Closed as completed** 2023-02-01 21:27 UTC
Labels: bug

**Comment by Spomky** [comment] 2023-02-02 13:26
Excellent! Many thanks for your feedback
