### ISSUE TITLE
Invalid attestation statement

### ISSUE THREAD

**Issue by Nevercold** [web-auth/webauthn-framework#372] opened 2023-01-24 23:58 UTC
Hello, 
I have updated from 4.4.1 to 4.5.0, 
now as soon as I add a device (Windows Hello), I get an error message "Invalid attestation statement." (web-auth/webauthn-lib/src/AuthenticatorAttestationResponseValidator.php:235) 

If I add a yubikey 5 it works.

My code: https://gist.github.com/Nevercold/f9b7527846c7db72c6bccc7a94867fcb
I tried to document the most important thing.

Unfortunately I didn't find anything about it in the docs.

I hope someone can help me.

Thanks!

**Comment by Spomky** [comment] 2023-01-25 05:41
Hi,

The 2 files look good and it is hard to say why this exception is thrown.
Could you please send me the option object and the authenticator response as JSON?

**Comment by Nevercold** [comment] 2023-01-25 09:21
Option
`{
    "rp": {
        "name": "test",
        "id": "domain.de"
    },
    "user": {
        "name": "Niekold",
        "id": "MQ",
        "displayName": "Jenny Rosen"
    },
    "challenge": "4IRIQDI8ESkrz8ThW_3eoA",
    "pubKeyCredParams": [
        {
            "type": "public-key",
            "alg": -7
        },
        {
            "type": "public-key",
            "alg": -46
        },
        {
            "type": "public-key",
            "alg": -35
        },
        {
            "type": "public-key",
            "alg": -36
        },
        {
            "type": "public-key",
            "alg": -257
        },
        {
            "type": "public-key",
            "alg": -258
        },
        {
            "type": "public-key",
            "alg": -259
        },
        {
            "type": "public-key",
            "alg": -37
        },
        {
            "type": "public-key",
            "alg": -38
        },
        {
            "type": "public-key",
            "alg": -39
        },
        {
            "type": "public-key",
            "alg": -260
        },
        {
            "type": "public-key",
            "alg": -261
        }
    ],
    "timeout": 60000,
    "excludeCredentials": [
        {
            "type": "public-key",
            "id": "YUBIKEY ....."
        }
    ],
    "authenticatorSelection": {
        "requireResidentKey": false,
        "userVerification": "discouraged",
        "authenticatorAttachment": "platform"
    },
    "attestation": "direct"
}`

Response
`{
    "rp": {
        "name": "test",
        "id": "domain.de"
    },
    "user": {
        "name": "Niekold",
        "id": "MQ",
        "displayName": "Jenny Rosen"
    },
    "challenge": "4IRIQDI8ESkrz8ThW_3eoA",
    "pubKeyCredParams": [
        {
            "type": "public-key",
            "alg": -7
        },
        {
            "type": "public-key",
            "alg": -46
        },
        {
            "type": "public-key",
            "alg": -35
        },
        {
            "type": "public-key",
            "alg": -36
        },
        {
            "type": "public-key",
            "alg": -257
        },
        {
            "type": "public-key",
            "alg": -258
        },
        {
            "type": "public-key",
            "alg": -259
        },
        {
            "type": "public-key",
            "alg": -37
        },
        {
            "type": "public-key",
            "alg": -38
        },
        {
            "type": "public-key",
            "alg": -39
        },
        {
            "type": "public-key",
            "alg": -260
        },
        {
            "type": "public-key",
            "alg": -261
        }
    ],
    "timeout": 60000,
    "excludeCredentials": [
        {
            "type": "public-key",
            "id": "Wxj326ZugB_8Vi6C2u1XLkU9Of862Atw5mUdcEdH5h0MI_kffl6cIzy8vi-PICTzhLDwLDoSGI-VwHjS55FVKg"
        }
    ],
    "authenticatorSelection": {
        "requireResidentKey": false,
        "userVerification": "discouraged",
        "authenticatorAttachment": "platform"
    },
    "attestation": "direct"
}`

Hope this helps :)

**Comment by Spomky** [comment] 2023-01-25 09:36
Many thanks.

The option object is fine, but the response is a copy-paste of the option object.

**Comment by Nevercold** [comment] 2023-01-25 09:38
sorry, my fault, I copied wrong...

```
{
  "id": "bh0lkwBt3zj8EFrsHMcb6hHNpUxfDnGwiM_Fg8_hnKc",
  "rawId": "bh0lkwBt3zj8EFrsHMcb6hHNpUxfDnGwiM_Fg8_hnKc",
  "response": {
    "attestationObject": "o2NmbXRmcGFja2VkZ2F0dFN0bXSiY2FsZzkBAGNzaWdZAQBjZUKqmBwRsUDei84mYY96BDBdMMNUz-akMIUDx40LMklfsxdRhy_oNkNUhbXcs_M81KvNhrCxP8dN0Ken-Iw7j9Rn0hGy4JNb73HfxvYF38vRZyWQXJgInkJv58KUYuVSswVmYPnAbunxM9qp-8sHDs6S_2TG0NZK_uwbvo7uoj-uCse6h4Fz8RV5_gHRLVkKIEjTZYLmY5yPpBTCjNuusVxd0RRybALSl-SfWTbYeY2UNE7L2Mxkd3uqegLKkJlVqpzb-ZPM5bUMsrhg9lCFUVsxnXQWyOOP2mTquOmJy_XmLs_7dU-2wNOmXCziEy7L2XiAWSgUIp3ApwcxxNg7aGF1dGhEYXRhWQFnV7vin6C3o2EJlznLw94xhx76CfsCuzNlPopT0i9FG59FAAAAAGAosBex1EwCtLOvza_Ja7IAIG4dJZMAbd84_BBa7BzHG-oRzaVMXw5xsIjPxYPP4ZynpAEDAzkBACBZAQCXVUCkY1qPTxyBHwuBCtxqiYXrwOZiAORC60WXNCAiNgAy0HoXpGYFejxuIAAGNQ9xnB53a5D5ZFJqE616fdWU7uGjTsUsDDyzwVouW8qgUhjW7hxTfdKVKWCRtI6YTAMjb0XHqQobSZ0dzpBalFPp4ditAGw5wn3H0X1_QoXiLIFiW29HYJdZT42teoe5k32XXdgc0KO6Tz8XMzFQdBLOLPtmbj116IhQeawkzB6WW-Zy7tiKeldtGz8knYt-xHyT8aVEU16FL8XhO_SZTTp3NWkj0jWoSbG8rxaPdP2z3tbotTU2egHhfCFeo0k0AgPN_xqf_WEb3jG08LI3lmU5IUMBAAE",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoidHZEREFkbk9pU2VCeGtuck1uNVI2dyIsIm9yaWdpbiI6Imh0dHBzOi8vd3d3LnB1aGdyb3VwLmRlIiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ",
    "transports": []
  },
  "type": "public-key",
  "clientExtensionResults": {},
  "authenticatorAttachment": "platform"
}
```

**Comment by Spomky** [comment] 2023-01-25 15:08
Hi,

I have tested with the input data you provided. Unfortunately, I was not able to reproduce with error.
The error comes from the verification of the authenticator attestation against the metadata statement you retreive through the `AttestationStatementSupportManager`.
I used the latest MDS from the FIDO Alliance (at https://fidoalliance.org/metadata/ - *Obtaining BLOB*) where the authenticator response is accepted and returned the following credential source:

```json
{
    "publicKeyCredentialId": "6oRgydKXdC3LtZBDoAXxKnWte68elEQejDrYOV9x-18",
    "type": "public-key",
    "transports": [],
    "attestationType": "none",
    "trustPath": {
        "type": "Webauthn\\TrustPath\\EmptyTrustPath"
    },
    "aaguid": "6028b017-b1d4-4c02-b4b3-afcdafc96bb2",
    "credentialPublicKey": "[REDACTED]",
    "userHandle": "[REDACTED]",
    "counter": 0,
    "otherUI": null
}
```

The AAGUID `6028b017-b1d4-4c02-b4b3-afcdafc96bb2` corresponds to the MSFT one *Windows Hello Software Authenticator*.

Can you check the MDS you use are the latest ones?

**Comment by Nevercold** [comment] 2023-01-25 15:14
Hey, ich habe mir das gestern abend auch schon angesehen gehabt, ich speichere mir alle X eine neue Kopie der Daten.
Die AAGUID ist vorhanden.
https://gist.github.com/Nevercold/f9b7527846c7db72c6bccc7a94867fcb#file-metadatastatementrepository-php

Maybe I have a mistake there?

**Comment by Nevercold** [comment] 2023-01-25 15:14
Hey, I had a look at this last night as well, I save myself a new copy of the data every X.
The AAGUID is present.
https://gist.github.com/Nevercold/f9b7527846c7db72c6bccc7a94867fcb#file-metadatastatementrepository-php

Maybe I have a mistake there?

Sorry for unclean code, haven't done it yet.

**Comment by Nevercold** [comment] 2023-01-25 15:16
![image](https://user-images.githubusercontent.com/32977558/214601459-9bb00379-7cd6-42cb-bb05-f120ad1c9a6d.png)

**Comment by Spomky** [comment] 2023-01-25 15:25
I am convinced there is something wrong with the MDS verification. #373 seems to be related to the same problem.
Let me dig into it.

**Comment by Nevercold** [comment] 2023-01-25 15:26
Thanks a lot! :)

**Comment by Spomky** [comment] 2023-01-25 20:43
I haven't made much progress, but I'm wondering if the problem could be with the OpenSSL check failing.
There are known incompatibilities with the new OpenSSL 3 and the PHP extension.
In the `Webauthn\AttestationStatement\TPMAttestationStatementSupport` class [starting at line 357](https://github.com/web-auth/webauthn-framework/blob/4.5.x/src/webauthn/src/AttestationStatement/TPMAttestationStatementSupport.php#L357-L364), the method returns `true` or `false` depending on the `openssl_verify` result.

Could you please:
1. Tell me the version of OpenSSL and the PHP extension you have on your platform (`php -i | grep OpenSSL`)?
2. make sure there is no error when verifying the signature?

Just replace lines 357 to 362 with the following lines of code:

```php
        //Clear existing errors
        while(openssl_error_string()) {}
        //Verify the signature
        $result = openssl_verify(
            $attestationStatement->get('certInfo'),
            $attestationStatement->get('sig'),
            $certificates[0],
            $opensslAlgorithmIdentifier
        );
        //Dump errors if any
        $errors = [];
        while($m = openssl_error_string()) {
            $errors[] = $m;
        }
        dump($result, $errors);
```

**Comment by Nevercold** [comment] 2023-01-25 21:19
Version is OpenSSL/1.1.1n
When replacing, no output comes. looks like this function will never be triggered.

**Comment by Spomky** [comment] 2023-01-26 07:36
> When replacing, no output comes. looks like this function will never be triggered.

Indeed, I mixed the attestation supports. We have a Packed Attn here, not a TPM one...
The file to modify in the `abstract class RSA` class from the `web-auth/cose-lib` package.

At line 37, change this

```php
        return openssl_verify($data, $signature, $key->toPublic()->asPem(), $this->getHashAlgorithm()) === 1;
```

Into that

```php
        while(openssl_error_string()){}
        $result = openssl_verify($data, $signature, $key->toPublic()->asPem(), $this->getHashAlgorithm()) === 1;
        $errors = [];
        while($m = openssl_error_string()){ $errors[] = $m; }
        dump($errors);
            
        return $result;
```

**Comment by Nevercold** [comment] 2023-01-26 21:06
There are 2x the same error: `error:0909006C:PEM routines:get_name:no start line`

**Comment by Nevercold** [comment] 2023-01-27 12:21
Could you do something on it already?

**Comment by Nevercold** [comment] 2023-01-27 15:38
if I manually overwrite this to true, it works fine.



I also noticed:
Apple devices (IPhone) it outputs the AAGUID 00000000-0000-0000-00000000.

I set with ->setResidentKey(AuthenticatorSelectionCriteria::RESIDENT_KEY_REQUIREMENT_REQUIRED), it to required. But the option-output still says "requireResidentKey": false

When I make a password-less login, it works with all except Yubikey. Windows says the key is not known.

**Comment by Spomky** [comment] 2023-01-31 18:25
OK I get it!
The `residentKey` parameter is not supported by every web browser. When you set `->setResidentKey(AuthenticatorSelectionCriteria::RESIDENT_KEY_REQUIREMENT_REQUIRED)`, it seems that you must also set `->setRequireResidentKey(true)`

This way, the property `requireResidentKey` will be set to `true` and `residentKey` to `required`.

Let me know if it solves the issue.

**Comment by Nevercold** [comment] 2023-01-31 18:26
And what about the other problems because of Windows Hello? :(

**Comment by Spomky** [comment] 2023-01-31 19:18
Honestly, I don't know. It seems to be related to the RSA algorithm, but none of the tests I ran gave me the same exception.
As I mentioned in https://github.com/web-auth/webauthn-framework/issues/374#issuecomment-1410926215, I need the input data sent to `openssl_verify`.
Could you please install `symfony/var-dumper` as a dev dependency and share the key as a raw and PEM value?

**Comment by Nevercold** [comment] 2023-01-31 23:51
Pem: 
```
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqAJDXHbYmqgrid/6woAfokC4tIAjTHnCYQHIfM6o5s4qt9JaJRIb
rMv2KxJch34XfFg17INBej9He1OkD/NmHJf7khM3cqEg1dmNPuEUKziW8dQJukjh
WtqjNWuZpRcdXH2kXFlYskQzwAa3LjcCdjYOtL9NZ45+I8jfRtgyn6ZiuLPCg5lS
aKQUQErgmXS4AUqQQ4lP9Ykwxdv2Gq4qAypcG9F/xT73JOq2UWvPq7r7OU6Nwpvm
W6uXX2gBnj3eL1WILTctjqR7ZcQRx28oYROaqot0QZ65rjrAaD30+hiDLaXjksvq
7A6Ym9mhoKY9i857A+SQqfcL/TClFCrZ1QIDAQAB
-----END RSA PUBLIC KEY-----
```

Key: 
```
object(Cose\Key\RsaKey)#187 (1) {
  ["data":"Cose\Key\Key":private]=>
  array(4) {
    [1]=>
    string(1) "3"
    [3]=>
    string(4) "-257"
    [-1]=>
    string(256) "�C\vؚ�+����@���#Ly�a�|Ψ��*��Z%���+\�~|X5�Az?G{S��f���7r� �ٍ>�+8���	�H�Zڣ5k��\}�\YX�D3��.7v6��Mg�~#��F�2��b���Rh�@J��t�J�C�O��0����**\��>�$�Qkϫ��9N��[��_h�=�/U�-7-��{e��o(a���tA���:�h=���-�������١��=��{䐩��0�*��"
    [-2]=>
    string(3) "
```

**Comment by Nevercold** [comment] 2023-02-01 00:00
which PHP version are you using? We use php8.1.14
is it perhaps because of that?

**Comment by lukewarlow** [comment] 2023-02-01 13:40
A possible fix for this is to pin web-auth/cose-lib to "4.0.12" this might fix the issues you have with RSA algorithm. I believe it's the same issue as #374. Version 4.1 of cose-lib is broken.

**Comment by Nevercold** [comment] 2023-02-01 17:15
Thank you! 
Fixed the problem.

**Comment by Spomky** [comment] 2023-02-02 13:27
Perfect!
@lukewarlow: is it fixed for you too?

**Comment by lukewarlow** [comment] 2023-02-02 13:32
I'm unable to easily test this now as we've decided to pin the dependency version to the lower version. However, the change looks to have test coverage, and others have said it works. 👍

**Comment by Spomky** [comment] 2023-02-02 13:34
Ok thank you. I am closing this topic for now.
Feel free to use it again or create a new one if needed.

**Closed as completed by Spomky** 2023-02-02 13:34 UTC
Labels: bug
